# 스프링 부트 기본 환경 선택(기본 profile: real,batch)
spring:
  profiles:
    active: real,batch
  quartz:
    #job-store-type: memory
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org.quartz.scheduler.skipUpdateCheck: true
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 3
      org.quartz.jobStore.class: org.quartz.simpl.RAMJobStore
      #https://www.techpaste.com/2016/03/quartz-scheduler-shutdown/
      #debug mode에서는 종료를 기다리지 않고 바로 끝나 버리는 문제가 있음. chromedriver.exe 가 떠 있는지 확인할 것!!!
      #org.quartz.threadPool.makeThreadsDaemons: true
      #org.quartz.scheduler.makeSchedulerThreadDaemon: true
      #org.quartz.scheduler.interruptJobsOnShutdown: true
      org.quartz.plugin.shutdownhook.class: org.quartz.plugins.management.ShutdownHookPlugin
      org.quartz.plugin.shutdownhook.cleanShutdown: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  output: 
    ansi:
      enabled: DETECT
  #Async 설정
  task:
    execution:
      pool:
        core-size: 4
        max-size: 40
        queue-capacity: 160
#server:
  #error:
    #path: /error2 #path를 바꿔도 계속 whitelabel로 나온다-_-
    #whitelabel:
      #enabled: false #tomcat default error 페이지 표시 : false인 경우
---
# mybatis 설정
mybatis:
  mapper-locations: classpath:sql/**/*.xml
  #config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.plantynet.tech2.vo
  configuration:
    #lazy-loading-enabled: true
    #aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
---
## 로그 설정파일 위치 지정
#스프링이나 일반 자바프로그램의 경우는 보통 logback.xml 파일을 resources 디렉토리에 만들어서 참조 (클래스 패스 루트상)
#logback은 이 설정파일을 자동으로 찾는데 logback.groovy -> logback-test.xml -> logback.xml 순서로 찾고 없으면 디폴트 설정을 따른다.
#스프링부트의 경우 조금 다르게 logback-spring.xml이라는 이름으로 설정하는데 그 이유는 logback.xml이라는 이름으로 하면
#스프링부트가 설정되기 전에 로그백 관련 설정을 해버리기 때문에 logback.xml이라는 이름 대신 logback-spring.xml을 사용한다.
#logback-spring.xml파일이 없다면 application.yml(.properties)파일의 설정을 보게됨.
logging:
  #아래처럼 logback-spring.xml를 다른 경로로 지정하는 방법도 있음
  #config: classpath:logback/logback-spring.xml
  path: /var/www/log/SpringBoot2Sample
  file: ${logging.path}/CONSOLE.log
  pattern:
    console: '[%d{yyyy-MM-dd HH:mm:ss}] %logger{10} %-5level [%thread] %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss}|%-5level|%msg%n'
  level:
    root: INFO
    org.mybatis.spring.SqlSessionUtils: DEBUG
    com.plantynet.tech2.dao: DEBUG
---
jasypt:
  encryptor:
    ##공개키 방식(RSA) 
    # a)개인키 생성
    # openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
    # b)공개키 생성
    # openssl rsa -pubout -in private_key.pem -out public_key.pem
    privateKeyFormat: PEM
    privateKeyLocation: classpath:private_key.pem
---
custom:
  array: 1, 2, 3
  #파라미터 없으면 에러 발생한다...
  #systemProperties: ${JASYPT_PASSWORD}
mail:
  host_name: mail.test.com
  port: 9000
  strList:
    - strList1
    - strList2
  strMap:
    name: strMap
    address: strMap@test.com
  mapList:
    - 
      name: test1
      address: test1@test.com
    - 
      name: test2
      address: test2@test.com