spring:
  profiles: real
  #resources:
    #static-locations: file:///${custom.adCheck.imgPath}
  datasource: 
    url: jdbc:mariadb://[ip]:3306/[db명]
    username: ENC(암호화된 db 접속 계정)
    password: ENC(암호화된 db 접속 비밀번호)
    driverClassName: org.mariadb.jdbc.Driver
    #dbcp2 https://www.mkyong.com/spring-boot/spring-boot-jdbc-oracle-database-commons-dbcp2-example/
    #type: org.apache.commons.dbcp2.BasicDataSource 
    #dbcp2:
      #max-total: 20
      #max-idle: 20
      #validation-query: select 1
      #test-on-borrow: false
      #test-while-idle: true
      #time-between-eviction-runs-millis: 600000
      #num-tests-per-eviction-run: 7
      #min-evictable-idle-time-millis: -1
    #hikari (type은 굳이 지정할 필요 없음)
    #type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connectionTimeout: 5000 #30000ms
      #maxLifetime: 1800000 #1800000ms(30분)
      maximumPoolSize: 20 #기본 10
      validationTimeout: 1000 #5000ms, connectionTimeout 보다 적어야 함
  jmx:
    enabled: false
  devtools:
    livereload:
      enabled: false
#정적인 내용도 자동 리로딩 되게 하기 위해 devtools에서 별도의 서버(port 35729)를 실행해서 
#브라우저와 연동함(브라우저 플러그인과 통신)
#필요 없으면 위에처럼 꺼야 함
  influxdb:
    url: http://127.0.0.1:8086
    database: NOAA_water_database
    username: ~
    password: ~
    retentionPolicy: autogen
---
server:
  port: 8188
---
custom:
  # 1시간에 한번
  schedule: '0 0 0/1 * * ?'
  # apache 등에서 static resoure 사용하기 위해...
  static:
    location: file:///D:/git/github/SpringBoot2WarSample/static